/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.majorproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ShowPerformance extends javax.swing.JFrame {
     public  Connection sqlConn = null;
  public   PreparedStatement pst =null;
   public ResultSet rs = null;

    /**
     * Creates new form ShowPerformance
     */
    public ShowPerformance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RollNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SubjectLabel1 = new javax.swing.JLabel();
        SubjectLabel4 = new javax.swing.JLabel();
        SubjectLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SubjectLabel2 = new javax.swing.JLabel();
        SubjectLabel3 = new javax.swing.JLabel();
        StudentName = new javax.swing.JTextField();
        StudentCourse = new javax.swing.JTextField();
        StudentReg = new javax.swing.JTextField();
        Subject1 = new javax.swing.JTextField();
        Subject2 = new javax.swing.JTextField();
        Subject3 = new javax.swing.JTextField();
        Subject4 = new javax.swing.JTextField();
        Subject5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AttendenceMarks = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CertificateMarks = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        OverallPerformance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CoursePerformance = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CertificatePerformance = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        AttendencePerformance = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Roll No");

        RollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please enter your  Reg No.");

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 23, 23));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reg No");

        SubjectLabel1.setForeground(new java.awt.Color(255, 255, 255));
        SubjectLabel1.setText("Subject1");

        SubjectLabel4.setForeground(new java.awt.Color(255, 255, 255));
        SubjectLabel4.setText("subjec4");

        SubjectLabel5.setForeground(new java.awt.Color(255, 255, 255));
        SubjectLabel5.setText("subject5");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Course");

        SubjectLabel2.setForeground(new java.awt.Color(255, 255, 255));
        SubjectLabel2.setText("subject2");

        SubjectLabel3.setForeground(new java.awt.Color(255, 255, 255));
        SubjectLabel3.setText("subject3");

        StudentName.setBackground(new java.awt.Color(0, 23, 23));
        StudentName.setForeground(new java.awt.Color(255, 255, 255));
        StudentName.setBorder(null);

        StudentCourse.setBackground(new java.awt.Color(0, 23, 23));
        StudentCourse.setForeground(new java.awt.Color(255, 255, 255));
        StudentCourse.setBorder(null);
        StudentCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentCourseActionPerformed(evt);
            }
        });

        StudentReg.setBackground(new java.awt.Color(0, 23, 23));
        StudentReg.setForeground(new java.awt.Color(255, 255, 255));
        StudentReg.setBorder(null);
        StudentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRegActionPerformed(evt);
            }
        });

        Subject1.setBackground(new java.awt.Color(0, 23, 23));
        Subject1.setForeground(new java.awt.Color(255, 255, 255));
        Subject1.setBorder(null);

        Subject2.setBackground(new java.awt.Color(0, 23, 23));
        Subject2.setForeground(new java.awt.Color(255, 255, 255));
        Subject2.setBorder(null);

        Subject3.setBackground(new java.awt.Color(0, 23, 23));
        Subject3.setForeground(new java.awt.Color(255, 255, 255));
        Subject3.setBorder(null);
        Subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject3ActionPerformed(evt);
            }
        });

        Subject4.setBackground(new java.awt.Color(0, 23, 23));
        Subject4.setForeground(new java.awt.Color(255, 255, 255));
        Subject4.setBorder(null);
        Subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject4ActionPerformed(evt);
            }
        });

        Subject5.setBackground(new java.awt.Color(0, 23, 23));
        Subject5.setForeground(new java.awt.Color(255, 255, 255));
        Subject5.setBorder(null);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Attendence Marks");

        AttendenceMarks.setBackground(new java.awt.Color(0, 23, 23));
        AttendenceMarks.setForeground(new java.awt.Color(255, 255, 255));
        AttendenceMarks.setBorder(null);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ceritificate Marks");

        CertificateMarks.setBackground(new java.awt.Color(0, 23, 23));
        CertificateMarks.setForeground(new java.awt.Color(255, 255, 255));
        CertificateMarks.setBorder(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Your over all performance is : ");

        OverallPerformance.setBackground(new java.awt.Color(0, 23, 23));
        OverallPerformance.setForeground(new java.awt.Color(255, 255, 255));
        OverallPerformance.setBorder(null);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Suggestion basis on your course performance : ");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Suggestion basis on your attendence performance :");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suggestion basis on your sports certificates :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Your performance ");

        CoursePerformance.setBackground(new java.awt.Color(0, 23, 23));
        CoursePerformance.setColumns(20);
        CoursePerformance.setForeground(new java.awt.Color(255, 255, 255));
        CoursePerformance.setRows(5);
        CoursePerformance.setBorder(null);
        jScrollPane1.setViewportView(CoursePerformance);

        CertificatePerformance.setBackground(new java.awt.Color(0, 23, 23));
        CertificatePerformance.setColumns(20);
        CertificatePerformance.setForeground(new java.awt.Color(255, 255, 255));
        CertificatePerformance.setRows(5);
        jScrollPane2.setViewportView(CertificatePerformance);

        AttendencePerformance.setBackground(new java.awt.Color(0, 23, 23));
        AttendencePerformance.setColumns(20);
        AttendencePerformance.setForeground(new java.awt.Color(255, 255, 255));
        AttendencePerformance.setRows(5);
        jScrollPane3.setViewportView(AttendencePerformance);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubjectLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SubjectLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SubjectLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SubjectLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AttendenceMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 151, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SubjectLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CertificateMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(647, 647, 647))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OverallPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(SubjectLabel1)
                    .addComponent(Subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectLabel4)
                    .addComponent(Subject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(SubjectLabel2)
                    .addComponent(Subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectLabel5)
                    .addComponent(Subject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(StudentCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubjectLabel3)
                    .addComponent(Subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(AttendenceMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(CertificateMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(OverallPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(RollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(371, 371, 371))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollNoActionPerformed

    private void StudentCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentCourseActionPerformed

    private void StudentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentRegActionPerformed

    private void Subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject3ActionPerformed

    private void Subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\
 
        
        	try{	String url
			= "jdbc:mysql://localhost:3306/connecter"; // table details
		String username = "root"; // MySQL credentials
		String password = "Happy@8438";
      System.out.print("sdfjhs");
		String query
			= "select *from student"; // query to be run
		Class.forName(
			"com.mysql.cj.jdbc.Driver"); // Driver name
		Connection con = DriverManager.getConnection(
			url, username, password);
		System.out.println(
			"Connection Established successfully");
		 String rollno = RollNo.getText().toString(); // Get the roll number value from the text field
            pst = con.prepareStatement("SELECT * FROM student WHERE ID = ?");
            pst.setString(1, rollno); // Set the roll number value
            rs = pst.executeQuery();
            if (rs.next()) {
                String col1 = rs.getString("StudentName");
                
                String col2 = rs.getString("ID");
                String col3 = rs.getString("course");
                  String col4 = rs.getString("subject1");
                  double sub1 = Double.parseDouble(col4);
                String col5 = rs.getString("subject2");
                 double sub2 = Double.parseDouble(col5);
                
                String col6 = rs.getString("subject3");
                 double sub3 = Double.parseDouble(col6);
                  String col7 = rs.getString("subject4");
                 double sub4 = Double.parseDouble(col7);
                String col8 = rs.getString("subject5");
               double sub5 = Double.parseDouble(col8);
                String col9 = rs.getString("attendence");
                double Atten = Double.parseDouble(col9);
                 String col10 = rs.getString("certificate");
                 double Certi =Double.parseDouble(col10);
                
                // Set the retrieved values into text fields
                StudentName.setText(col1);
                StudentReg.setText(col2);
                StudentCourse.setText(col3);
                Subject1.setText(col4);
                Subject2.setText(col5);
                 Subject3.setText(col6);
                Subject4.setText(col7);
                 Subject5.setText(col8);
                AttendenceMarks.setText(col9);
                 CertificateMarks.setText(col10);
                 
              double overAllPersent =  (sub1+sub2+sub3+sub4+sub5)/5;               
                 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            
                 
                 
                 if (overAllPersent > 95) {
JOptionPane.showMessageDialog(null, "you are not eligible for Attendence is above 95");


} else if (Atten > 90&&Atten<95) {
//attendanceMarks += 2;
overAllPersent= overAllPersent+2;
AttendenceMarks.setText("2");
} else if (Atten > 80&&Atten<90) {
//attendanceMarks += 1.5;
overAllPersent=overAllPersent+1.5;
AttendenceMarks.setText("1.5");
} else if (Atten > 70&&Atten<80) {
//attendanceMarks += 1;
AttendenceMarks.setText("1");
overAllPersent=overAllPersent+1;
} else if (Atten > 60&&Atten<70) {
//attendanceMarks += 0.5;
AttendenceMarks.setText("0.5");
overAllPersent =overAllPersent+0.5;

}
else{
    JOptionPane.showMessageDialog(null, "you are not eligible for Attendence bonus besause your attendence is less 60");
}
                 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                 
          if (overAllPersent > 90) {
              JOptionPane.showMessageDialog(null, "Your marks already good so you are not applicable for sports bonus");
} else {
if (Certi == 1) {

CertificateMarks.setText("1");
overAllPersent=overAllPersent+1;
} else if (Certi == 2) {
overAllPersent=overAllPersent+2;
CertificateMarks.setText("2");
} else if (Certi >= 3) {
overAllPersent=overAllPersent+3;
CertificateMarks.setText("3");
} else
{
   CertificateMarks.setText("NULL");
}}                
                String Overall = String.valueOf(overAllPersent);
      OverallPerformance.setText(Overall);
                 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                 
              
if(Atten < 60) {
AttendencePerformance.setText("You need to focus more on your attendance. Your attendance is very low, and it's important to attend all regular classes.");

} else if (Atten < 70 && overAllPersent > 60) {
AttendencePerformance.setText("You are making some progress with your attendance, but there is still room for improvement.");

} else if (Atten < 80 && overAllPersent > 70) {
AttendencePerformance.setText("You are doing well in your studies and have a good chance of achieving an attendance certificate. Keep up the good work!");

} else if (Atten < 90 && overAllPersent > 80) {
AttendencePerformance.setText("You are an excellent student and have a very high chance of achieving an attendance certificate. Keep it up!");

} else {
AttendencePerformance.setText("Your attendance is outstanding! You have already secured an attendance certificate.");
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

if (overAllPersent < 60) {
CoursePerformance.setText("You need to work harder and improve your overall marks. Try to study regularly and focus on your weak areas.");
} else if (overAllPersent < 70) {
CoursePerformance.setText("You are making progress, but there is still room for improvement in your overall marks. Try to study regularly and focus on your weak areas.");
} else if (overAllPersent < 80) {
CoursePerformance.setText("You are doing well in your studies, but there is still scope for improvement in your overall marks. Try to study regularly and focus on your weak areas.");
} else if (overAllPersent < 90) {
CoursePerformance.setText("You are an excellent student, but there is always room for improvement in your overall marks. Keep working hard and aim for even higher scores.");
} else {
CoursePerformance.setText("Your overall marks are outstanding! Keep up the exceptional work.");
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////     
                 
          if ( Certi==0) {
CertificatePerformance.setText("You need to focus more on attending sports activities. Your participation is very low, and it's important to attend all scheduled sports events.");

} else if (Certi==1) {
CertificatePerformance.setText("You are making some progress with your sports participation, but there is still room for improvement.");

} else if (Certi==2) {
CertificatePerformance.setText("You are doing well in sports and have a good chance of earning a sports certificate. Keep up the good work!");

} else if (Certi==3) {
CertificatePerformance.setText("You are an excellent participant in sports and have a very high chance of earning a sports certificate. Keep it up!");

} else {
CertificatePerformance.setText("Your sports performance is outstanding! You have already secured a sports certificate.");
}       
                 
                 
                 
                 
             
            } else {
                // Handle the case when the roll number is not found in the table
                JOptionPane.showMessageDialog(null, "Roll number not found in the database.");
            }
        } catch (Exception ex) {
            Logger.getLogger(ShowPerformance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPerformance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AttendenceMarks;
    private javax.swing.JTextArea AttendencePerformance;
    private javax.swing.JTextField CertificateMarks;
    private javax.swing.JTextArea CertificatePerformance;
    private javax.swing.JTextArea CoursePerformance;
    private javax.swing.JTextField OverallPerformance;
    private javax.swing.JTextField RollNo;
    private javax.swing.JTextField StudentCourse;
    private javax.swing.JTextField StudentName;
    private javax.swing.JTextField StudentReg;
    private javax.swing.JTextField Subject1;
    private javax.swing.JTextField Subject2;
    private javax.swing.JTextField Subject3;
    private javax.swing.JTextField Subject4;
    private javax.swing.JTextField Subject5;
    private javax.swing.JLabel SubjectLabel1;
    private javax.swing.JLabel SubjectLabel2;
    private javax.swing.JLabel SubjectLabel3;
    private javax.swing.JLabel SubjectLabel4;
    private javax.swing.JLabel SubjectLabel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
